# Generated by Django 5.0.14 on 2025-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono_casa', models.CharField(max_length=15)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('password', models.CharField(max_length=128)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
