# Generated by Django 5.0.14 on 2025-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='comision',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(upload_to='fotos_trabajadores/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sueldo_base',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sueldo_bruto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
