# Generated by Django 5.0.14 on 2025-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_alter_trabajador_comision_alter_trabajador_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='sueldo_bruto',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(upload_to='trabajadores_fotos/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sueldo_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_casa',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_movil',
            field=models.CharField(max_length=9),
        ),
    ]
