# Generated by Django 5.0.14 on 2025-07-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_options_remove_trabajador_eliminado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={},
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_trabajadores/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_movil',
            field=models.CharField(max_length=15),
        ),
    ]
