# Generated by Django 5.0.14 on 2025-08-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_ciudad_provincia_trabajador_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajadores.ciudad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(upload_to='fotos_trabajadores/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajadores.provincia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_casa',
            field=models.CharField(max_length=15),
        ),
    ]
