# Generated by Django 5.0.14 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0006_alter_trabajador_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
