# Generated by Django 5.0.14 on 2025-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0007_alter_trabajador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
