# Generated by Django 5.0.14 on 2025-08-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0008_alter_trabajador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
