# Generated by Django 5.0.14 on 2025-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0009_alter_trabajador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(default='Dirección pendiente', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
